### PR TITLE
Add the line return.

### PR DESCRIPTION
**Pull request by JulesGM**
See https://github.com/mbarkhau/pretty-traceback/issues/3

### CODE REVIEW

**Comment by JulesGM** [comment]
I just want to add that I don't see the error  message at all without this

**Comment by JulesGM** [comment]
@mbarkhau

**Comment by JulesGM** [comment]
Great library btw! really cool work.

**Comment by mbarkhau** [comment]
Merged separately, due to my inability to deal with git.

**Comment by JulesGM** [comment]
that's great, thanks.

**Pull request closed without merging**
